server:
  port: 8090

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: produits-route
          uri: lb://produits-service
          predicates:
            - Path=/api/produits/**

        - id: categories-route
          uri: lb://produits-service
          predicates:
            - Path=/api/categories/**

        - id: avis-route
          uri: lb://avis-service
          predicates:
            - Path=/api/avis/**

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
  instance:
    prefer-ip-address: true
